# Generated by Django 4.2.5 on 2024-06-30 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsede',
            name='nombre',
            field=models.CharField(choices=[('Oscar Lucero Moya', 'Oscar Lucero'), ('Celia Sanchez', 'Celia Sanchez'), ('Manuel Fajardo', 'Manuel Fajardo'), ('Pedagogico', 'Pedagogico')], db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(choices=[('Oscar Lucero Moya', 'Oscar Lucero'), ('Celia Sanchez', 'Celia Sanchez'), ('Manuel Fajardo', 'Manuel Fajardo'), ('Pedagogico', 'Pedagogico')], max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='HistoricalCentrosCostos',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=150)),
                ('codigo', models.CharField(db_index=True, max_length=150)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('departamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Principal.departamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('jefe', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'rol': 'Jefe de Area'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'rol': 'Responsable'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'rol': 'Supervisor'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical centros costos',
                'verbose_name_plural': 'historical centros costoss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
